name: build

on:
  push:
  workflow_dispatch:                                  # Allow to manually trigger workflow.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # rusty_libimobiledevice
      ## libusbmuxd
      - name: Install rusty_libimboiledevice dependencies
        run: sudo apt-get install build-essential pkg-config checkinstall git autoconf automake libtool-bin libplist-dev libimobiledevice-glue-dev usbmuxd
      - name: Clone libusbmuxd
        run: git clone https://github.com/libimobiledevice/libusbmuxd.git && cd libusbmuxd && ./autogen.sh && make && sudo make install
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
